// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Linn.Portal.Authorization.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Linn.Portal.Persistence.Authorization.Migrations
{

    [DbContext(typeof(ServiceDbContext))]
    [Migration("20250812072620_InitialAuthorization")]
    partial class InitialAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedResource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubjectSub")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectSub");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectSub")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("SubjectSub");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Subject", b =>
                {
                    b.Property<Guid>("Sub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Sub");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Association", b =>
                {
                    b.HasOne("Linn.Portal.Domain.Authorization.Subject", "Subject")
                        .WithMany("Associations")
                        .HasForeignKey("SubjectSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Permission", b =>
                {
                    b.HasOne("Linn.Portal.Domain.Authorization.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linn.Portal.Domain.Authorization.Subject", "Subject")
                        .WithMany("Permissions")
                        .HasForeignKey("SubjectSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Linn.Portal.Domain.Authorization.Subject", b =>
                {
                    b.Navigation("Associations");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
